<a href="https://colab.research.google.com/github/dhairyaramani747/Machine_learning_7212/blob/main/P4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("/content/01 covid_toy (1).csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
print(df.cough.value_counts())

print()
print()

print(df.city.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64


city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
x=df.iloc[:,0:5]
y=df.drop(x,axis='columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age gender  fever cough       city
64   42   Male  104.0  Mild     Mumbai
41   82   Male    NaN  Mild    Kolkata
14   51   Male  104.0  Mild  Bangalore
30   15   Male  101.0  Mild      Delhi
82   24   Male   98.0  Mild    Kolkata


   has_covid
64        No
41       Yes
14        No
30       Yes
82       Yes

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [12]:
si=SimpleImputer()
le=LabelEncoder()

In [17]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.fit_transform(y_test['has_covid'])

In [18]:
x_train['fever'] = si.fit_transform(x_train[['fever']])

In [19]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False)

In [22]:
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [24]:
x_train

    age  gender       fever   cough       city
64   42    Male  104.000000    Mild     Mumbai
41   82    Male  100.901408    Mild    Kolkata
14   51    Male  104.000000    Mild  Bangalore
30   15    Male  101.000000    Mild      Delhi
82   24    Male   98.000000    Mild    Kolkata
..  ...     ...         ...     ...        ...
73   34    Male   98.000000  Strong    Kolkata
48   66    Male   99.000000  Strong  Bangalore
0    60    Male  103.000000    Mild    Kolkata
78   11    Male  100.000000    Mild  Bangalore
83   17  Female  104.000000    Mild    Kolkata

[80 rows x 5 columns]

In [25]:
transformer = [('trans1',SimpleImputer(),['fever']),
               ('trans2',OrdinalEncoder(categories = [['Mild','Strong']]),['cough']),
               ('trans3',OneHotEncoder(sparse_output = False,drop = 'first'),['gender','city'])]

In [26]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = transformer,remainder = 'passthrough').set_output(transform = 'pandas')

In [27]:
x_train_transformed = ct.fit_transform(x_train)

In [28]:
x_train_trans = ct.fit_transform(x_train)

In [29]:
x_train_trans.sample(5)

,trans1__fever,trans2__cough,trans3__gender_Male,trans3__city_Delhi,trans3__city_Kolkata,trans3__city_Mumbai,remainder__age
25,100.901408,0.0,1.0,0.0,0.0,1.0,23
97,101.000000,0.0,0.0,0.0,0.0,0.0,20
80,99.000000,0.0,0.0,0.0,0.0,1.0,14
87,101.000000,1.0,1.0,0.0,0.0,0.0,47
76,100.000000,0.0,1.0,0.0,0.0,0.0,80

In [30]:
X_test_trans=ct.transform(x_test)

In [31]:
x_train_trans.shape

(80, 7)

In [34]:
print(x_train_trans.sample(5))
print()
print()
print(X_test_trans.shape)

    trans1__fever  trans2__cough  trans3__gender_Male  trans3__city_Delhi  \
37     100.000000            0.0                  1.0                 0.0
71     104.000000            1.0                  0.0                 1.0
91     100.901408            0.0                  1.0                 1.0
61      98.000000            1.0                  0.0                 0.0
64     104.000000            0.0                  1.0                 0.0

    trans3__city_Kolkata  trans3__city_Mumbai  remainder__age
37                   1.0                  0.0              55
71                   0.0                  0.0              75
91                   0.0                  0.0              38
61                   0.0                  1.0              81
64                   0.0                  1.0              42


(20, 7)